# Generated by Django 4.0.3 on 2023-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Processing', 'Processing'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='unpaid', max_length=20),
        ),
    ]
