# Generated by Django 4.0.3 on 2023-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_stage_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.URLField()),
                ('cover_photo', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
