# Generated by Django 4.0.3 on 2023-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_ip_product_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
