# Generated by Django 4.0.3 on 2023-07-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.CharField(max_length=255)),
                ('is_popular', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rp', models.CharField(max_length=255)),
                ('dp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('is_best_seller', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=255)),
                ('value', models.ManyToManyField(to='products.option')),
            ],
        ),
        migrations.CreateModel(
            name='SubVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.schema')),
            ],
        ),
        migrations.CreateModel(
            name='SubVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.CharField(max_length=255)),
                ('is_popular', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rp', models.CharField(max_length=255)),
                ('dp', models.CharField(max_length=255)),
                ('price', models.ManyToManyField(to='products.price')),
                ('subvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subvariant')),
            ],
        ),
        migrations.AddField(
            model_name='subvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.ManyToManyField(to='products.price'),
        ),
        migrations.AddField(
            model_name='option',
            name='subvariant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subvariant'),
        ),
    ]
