# Generated by Django 4.0.3 on 2023-07-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_schema_layout_remove_subvariant_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='value',
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='subvariantoption',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subvariantoption',
            name='subvariant',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='schema',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='SubVariant',
        ),
        migrations.DeleteModel(
            name='SubVariantOption',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
