# Generated by Django 4.0.3 on 2023-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_schema_value_remove_subvariant_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starting_price',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='starting_quantity',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
