# Generated by Django 4.0.3 on 2023-07-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_dp_alter_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='information',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
