# Generated by Django 4.0.3 on 2023-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_cover_category_information_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='information',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
