# Generated by Django 4.0.3 on 2023-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_ideas_product_perfect_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intro_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
