# Generated by Django 4.0.3 on 2023-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
