# Generated by Django 4.0.3 on 2023-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
