# Generated by Django 4.0.3 on 2023-09-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_photo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
